export const techCategories = {
  frontend: {
    name: "Frontend Development",
    categories: [
      {
        name: "JavaScript Basics",
        topics: [
          "Variables & Data Types",
          "Operators",
          "Control Flow",
          "Functions",
          "Arrays",
          "Objects",
          "Scope & Hoisting",
          "this Keyword",
          "Events",
          "Basic DOM Operations",
        ],
      },
      {
        name: "React",
        topics: [
          "Components & Props",
          "State & Lifecycle",
          "Hooks",
          "Context API",
          "React Router",
          "Redux",
          "Forms & Controlled Components",
          "Performance Optimization",
          "Error Boundaries",
          "Server-Side Rendering",
          "Testing React Apps",
          "Custom Hooks",
          "Component Patterns",
          "React Query",
          "Styling in React",
        ],
      },
      {
        name: "DOM Manipulation",
        topics: [
          "Selectors",
          "Event Handling",
          "DOM Traversal",
          "Creating Elements",
          "Modifying Elements",
          "Event Delegation",
          "DOM Animation",
          "Form Handling",
          "Custom Events",
          "Shadow DOM",
        ],
      },
    ],
  },
  languages: {
    name: "Programming Languages",
    categories: [
      {
        name: "JavaScript Modern Features",
        topics: [
          "Arrow Functions",
          "Template Literals",
          "Destructuring",
          "Spread/Rest Operators",
          "Classes",
          "Modules",
          "Promises",
          "async/await",
          "Generators",
          "Map & Set",
        ],
      },
      {
        name: "Python",
        topics: [
          "Python Basics",
          "Data Types & Variables",
          "Control Structures",
          "Functions & Lambda",
          "Lists & Tuples",
          "Dictionaries & Sets",
          "Object-Oriented Programming",
          "Modules & Packages",
          "File Handling",
          "Exception Handling",
          "List Comprehension",
          "Decorators & Generators",
          "Virtual Environments",
          "Libraries & Frameworks",
          "Testing in Python",
        ],
      },
    ],
  },
  backend: {
    name: "Backend Development",
    categories: [
      {
        name: "Node.js",
        topics: [
          "Modules",
          "File System",
          "Streams",
          "Events",
          "HTTP/HTTPS",
          "Express",
          "Database Integration",
          "Authentication",
          "Middleware",
          "API Development",
        ],
      },
    ],
  },
  programming_concepts: {
    name: "Programming Concepts",
    categories: [
      {
        name: "Object-Oriented JavaScript",
        topics: [
          "Prototypes",
          "Classes",
          "Inheritance",
          "Encapsulation",
          "Polymorphism",
          "Constructor Functions",
          "Instance Methods",
          "Static Methods",
          "Private Fields",
          "Mixins",
        ],
      },
      {
        name: "Functional Programming",
        topics: [
          "Pure Functions",
          "Immutability",
          "Higher-Order Functions",
          "Closures",
          "Currying",
          "Composition",
          "Recursion",
          "Map/Reduce/Filter",
          "Functors",
          "Monads",
        ],
      },
      {
        name: "Data Structures",
        topics: [
          "Arrays",
          "Objects",
          "Sets",
          "Maps",
          "Linked Lists",
          "Stacks",
          "Queues",
          "Trees",
          "Graphs",
          "Hash Tables",
        ],
      },
      {
        name: "Algorithms",
        topics: [
          "Sorting",
          "Searching",
          "Recursion",
          "Dynamic Programming",
          "Graph Algorithms",
          "Tree Traversal",
          "String Manipulation",
          "Array Operations",
          "Time Complexity",
          "Space Complexity",
        ],
      },
    ],
  },
  development_practices: {
    name: "Development Practices",
    categories: [
      {
        name: "Testing",
        topics: [
          "Unit Testing",
          "Integration Testing",
          "E2E Testing",
          "Jest",
          "Mocha",
          "Cypress",
          "Test Coverage",
          "Mocking",
          "TDD",
          "BDD",
        ],
      },
      {
        name: "Security",
        topics: [
          "XSS Prevention",
          "CSRF Protection",
          "Input Validation",
          "Authentication",
          "Authorization",
          "Secure Headers",
          "Content Security Policy",
          "HTTPS",
          "SQL Injection",
          "Security Headers",
        ],
      },
      {
        name: "Best Practices",
        topics: [
          "Code Style",
          "Documentation",
          "Version Control",
          "Code Review",
          "Clean Code",
          "Refactoring",
          "Design Principles",
          "Performance",
          "Security",
          "Accessibility",
        ],
      },
    ],
  },
  tooling: {
    name: "Development Tools",
    categories: [
      {
        name: "Build Tools",
        topics: [
          "Webpack",
          "Babel",
          "Vite",
          "Rollup",
          "ESLint",
          "Prettier",
          "npm Scripts",
          "Grunt",
          "Gulp",
          "TypeScript",
        ],
      },
      {
        name: "Package Management",
        topics: [
          "npm",
          "yarn",
          "pnpm",
          "package.json",
          "Dependencies",
          "DevDependencies",
          "Versioning",
          "Scripts",
          "Workspaces",
          "Monorepos",
        ],
      },
    ],
  },
};
